// Generated by scripts/sync-nanoka-echoes.mjs. Do not edit.
export const catalogProvenance={"sources":{"characters":"https://static.nanoka.cc/ww/3.7/character.json","weapons":"https://static.nanoka.cc/ww/3.7/weapon.json","echoes":"https://static.nanoka.cc/ww/3.7/echo.json","titles":"https://api-v2.encore.moe/api/en/title"},"dataVersion":"3.7","generatedAt":"2026-10-01T09:04:09.090Z"} as const
