// Generated by scripts/sync-nanoka-echoes.mjs. Do not edit.
export const catalogProvenance={"sources":{"characters":"https://static.nanoka.cc/ww/3.6/character.json","weapons":"https://static.nanoka.cc/ww/3.6/weapon.json","echoes":"https://static.nanoka.cc/ww/3.6/echo.json","titles":"https://api-v2.encore.moe/api/en/title"},"dataVersion":"3.6","generatedAt":"2026-08-18T13:02:33.895Z"} as const
